source 'https://github.com/CocoaPods/Specs.git'


target 'TFIntentions', :exclusive => true do
  pod "TFIntentions", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "TFIntentions", :path => "../"
  pod 'Specta', :git => "https://github.com/specta/specta.git", :tag => "v0.3.0.beta1"
  pod 'Expecta',     '~> 0.2.4'
  pod "OCMockito"
  
end
